print("******************************************\n")
print("Welcome to the Greeting App!")
print("******************************************\n")
name = input("Please enter your name: ")
color = input("What is your favorite color? ")
print(f"Hello, {name}! {color} is a beautiful color!")
print("Thank you for using the Greeting App!")
print("******************************************\n")
print("Goodbye!")